package server
import "net/http"
func(s *Server)dashboard(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(dashHTML))}
const dashHTML=`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Exchequer</title>
<style>:root{--bg:#1a1410;--bg2:#241e18;--bg3:#2e261e;--rust:#c45d2c;--rl:#e8753a;--leather:#a0845c;--cream:#f0e6d3;--cm:#7a7060;--gold:#d4a843;--green:#4a9e5c;--mono:'JetBrains Mono',Consolas,monospace;--serif:'Libre Baskerville',Georgia,serif}*{margin:0;padding:0;box-sizing:border-box}body{background:var(--bg);color:var(--cream);font-family:var(--mono);font-size:13px;line-height:1.6}.hdr{padding:.6rem 1.2rem;border-bottom:1px solid var(--bg3);display:flex;justify-content:space-between;align-items:center}.hdr h1{font-family:var(--serif);font-size:1rem}.hdr h1 span{color:var(--rl)}.sub{font-size:.65rem;color:var(--cm)}.main{max-width:700px;margin:0 auto;padding:1rem}.search{width:100%;background:var(--bg2);border:1px solid var(--bg3);color:var(--cream);padding:.4rem .6rem;font-family:var(--mono);font-size:.78rem;margin-bottom:.6rem;outline:none}.search:focus{border-color:var(--rust)}.stats{display:flex;gap:1rem;margin-bottom:.8rem;flex-wrap:wrap}.stat{text-align:center}.stat-n{font-size:1.2rem;color:var(--rl);font-family:var(--serif)}.stat-l{font-size:.55rem;color:var(--cm);text-transform:uppercase;letter-spacing:1px}.btn{font-family:var(--mono);font-size:.68rem;padding:.3rem .6rem;border:1px solid;cursor:pointer;background:transparent}.btn-p{border-color:var(--rust);color:var(--rl)}.btn-p:hover{background:var(--rust);color:var(--cream)}.item{background:var(--bg2);border:1px solid var(--bg3);padding:.6rem;margin-bottom:.3rem;cursor:pointer;transition:border-color .15s}.item:hover{border-color:var(--leather)}.item h3{font-size:.82rem;margin-bottom:.15rem}.item-meta{font-size:.65rem;color:var(--cm);display:flex;gap:.5rem;flex-wrap:wrap}.empty{text-align:center;padding:2rem;color:var(--cm);font-style:italic;font-family:var(--serif)}.modal-bg{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.65);display:flex;align-items:center;justify-content:center;z-index:100}.modal{background:var(--bg2);border:1px solid var(--bg3);padding:1.5rem;width:90%;max-width:500px;max-height:90vh;overflow-y:auto}.modal h2{font-family:var(--serif);font-size:.9rem;margin-bottom:1rem}label.fl{display:block;font-size:.65rem;color:var(--leather);text-transform:uppercase;letter-spacing:1px;margin-bottom:.2rem;margin-top:.5rem}input[type=text],input[type=number]{background:var(--bg);border:1px solid var(--bg3);color:var(--cream);padding:.35rem .5rem;font-family:var(--mono);font-size:.78rem;width:100%;outline:none}.del{color:var(--cm);cursor:pointer;font-size:.65rem;float:right}.del:hover{color:var(--rust)}</style></head>
<body><div class="hdr"><div><h1><span>Stockyard</span> Exchequer</h1><div class="sub">Self-hosted budget tracker</div></div><button class="btn btn-p" onclick="showModal()">+ New</button></div>
<div class="main"><div id="upgrade-banner" style="display:none;background:#241e18;border:1px solid #8b3d1a;border-left:3px solid #c45d2c;padding:.6rem 1rem;font-size:.78rem;color:#bfb5a3;margin-bottom:.8rem"><strong style="color:#f0e6d3">Free tier</strong> — 10 items max. <a href="https://stockyard.dev/exchequer/" target="_blank" style="color:#e8753a">Upgrade to Pro →</a></div><div class="stats" id="stats"></div>
<input class="search" id="search" placeholder="Search budgets..." oninput="debounceSearch()">
<div id="list"></div></div>
<div class="modal-bg" id="modal" style="display:none" onclick="if(event.target===this)hideModal()"><div class="modal"><h2 id="mt">New Budget</h2>
<label class="fl">Name</label><input type="text" id="f-name" placeholder="Name"><label class="fl">Category</label><input type="text" id="f-category" placeholder="Category"><label class="fl">Allocated</label><input type="number" id="f-allocated" placeholder="Allocated"><label class="fl">Spent</label><input type="number" id="f-spent" placeholder="Spent"><label class="fl">Period</label><input type="text" id="f-period" placeholder="Period"><label class="fl">Start Date</label><input type="text" id="f-start_date" placeholder="Start Date"><label class="fl">End Date</label><input type="text" id="f-end_date" placeholder="End Date"><label class="fl">Notes</label><input type="text" id="f-notes" placeholder="Notes">
<div style="margin-top:1rem;display:flex;gap:.5rem"><button class="btn btn-p" onclick="save()">Save</button><button class="btn" style="color:var(--cm);border-color:var(--bg3)" onclick="hideModal()">Cancel</button></div></div></div>
<script>
const API="/api/budgets";let editId=null,timer=null,curFilter="";

function showModal(id){editId=id||null;document.getElementById("mt").textContent=id?"Edit":"New";if(id){fetch(API+"/"+id).then(r=>r.json()).then(e=>{document.getElementById("f-name").value=e.name||"";document.getElementById("f-category").value=e.category||"";document.getElementById("f-allocated").value=e.allocated||"";document.getElementById("f-spent").value=e.spent||"";document.getElementById("f-period").value=e.period||"";document.getElementById("f-start_date").value=e.start_date||"";document.getElementById("f-end_date").value=e.end_date||"";document.getElementById("f-notes").value=e.notes||"";})}else{document.getElementById("f-name").value="";document.getElementById("f-category").value="";document.getElementById("f-allocated").value="";document.getElementById("f-spent").value="";document.getElementById("f-period").value="";document.getElementById("f-start_date").value="";document.getElementById("f-end_date").value="";document.getElementById("f-notes").value=""}document.getElementById("modal").style.display="flex"}
function hideModal(){document.getElementById("modal").style.display="none";editId=null}
function debounceSearch(){clearTimeout(timer);timer=setTimeout(load,300)}
function filterBy(v){curFilter=v;load()}
async function loadStats(){const r=await fetch("/api/stats");const d=await r.json();const el=document.getElementById("stats");let h='<div class="stat"><div class="stat-n">'+d.total+'</div><div class="stat-l">Total</div></div>';if(d.by_status){for(const[k,v]of Object.entries(d.by_status)){h+='<div class="stat"><div class="stat-n" style="color:'+stc(k)+'">'+v+'</div><div class="stat-l">'+k.replace(/_/g," ")+'</div></div>'}};el.innerHTML=h}
async function load(){let url=API;const q=document.getElementById("search").value;const p=[];if(q)p.push("q="+encodeURIComponent(q));if(curFilter)p.push("status="+curFilter);if(p.length)url+="?"+p.join("&");const r=await fetch(url);const d=await r.json();const items=d.budgets||[];const el=document.getElementById("list");if(!items.length){el.innerHTML='<div class="empty">No budgets yet</div>';loadStats();return}
el.innerHTML=items.map(e=>{return '<div class="item" ondblclick="showModal(\''+e.id+'\')"><span class="del" onclick="event.stopPropagation();del(\''+e.id+'\')">x</span><h3>'+e.name+'</h3><div class="item-meta"><span>${e.category||"\u2014"}</span><span>$${(e.allocated/100).toFixed(2)}</span><span>$${(e.spent/100).toFixed(2)}</span><span>${e.period||"\u2014"}</span></div></div>'}).join("");loadStats()}
async function save(){const body={"name":document.getElementById("f-name").value,"category":document.getElementById("f-category").value,"allocated":parseInt(document.getElementById("f-allocated").value)||0,"spent":parseInt(document.getElementById("f-spent").value)||0,"period":document.getElementById("f-period").value,"start_date":document.getElementById("f-start_date").value,"end_date":document.getElementById("f-end_date").value,"notes":document.getElementById("f-notes").value};const method=editId?"PUT":"POST";const url=editId?API+"/"+editId:API;await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});hideModal();load()}
async function del(id){await fetch(API+"/"+id,{method:"DELETE"});load()}
load();loadStats()
fetch('/api/tier').then(r=>r.json()).then(j=>{if(j.tier==='free'){var b=document.getElementById('upgrade-banner');if(b)b.style.display='block'}}).catch(()=>{var b=document.getElementById('upgrade-banner');if(b)b.style.display='block'});
</script></body></html>`
