package store
import("database/sql";"fmt";"os";"path/filepath";"time";_ "modernc.org/sqlite")
type DB struct{*sql.DB}
type Budget struct{ID int64 `json:"id"`;Name string `json:"name"`;Department string `json:"department"`;BudgetCents int64 `json:"budget_cents"`;SpentCents int64 `json:"spent_cents"`;Period string `json:"period"`;CreatedAt time.Time `json:"created_at"`}
type Actual struct{ID int64 `json:"id"`;BudgetID int64 `json:"budget_id"`;Description string `json:"description"`;AmountCents int64 `json:"amount_cents"`;Date string `json:"date"`;CreatedAt time.Time `json:"created_at"`}
func Open(d string)(*DB,error){os.MkdirAll(d,0755);dsn:=filepath.Join(d,"exchequer.db")+"?_journal_mode=WAL&_busy_timeout=5000";db,err:=sql.Open("sqlite",dsn);if err!=nil{return nil,fmt.Errorf("open: %w",err)};db.SetMaxOpenConns(1);migrate(db);return &DB{db},nil}
func migrate(db *sql.DB){db.Exec(`CREATE TABLE IF NOT EXISTS budgets(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,department TEXT DEFAULT '',budget_cents INTEGER NOT NULL,spent_cents INTEGER DEFAULT 0,period TEXT NOT NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS actuals(id INTEGER PRIMARY KEY AUTOINCREMENT,budget_id INTEGER NOT NULL,description TEXT NOT NULL,amount_cents INTEGER NOT NULL,date TEXT DEFAULT '',created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`)}
func(db *DB)CreateBudget(b *Budget)error{res,err:=db.Exec(`INSERT INTO budgets(name,department,budget_cents,period)VALUES(?,?,?,?)`,b.Name,b.Department,b.BudgetCents,b.Period);if err!=nil{return err};b.ID,_=res.LastInsertId();return nil}
func(db *DB)ListBudgets()([]Budget,error){rows,_:=db.Query(`SELECT b.id,b.name,b.department,b.budget_cents,COALESCE(SUM(a.amount_cents),0),b.period,b.created_at FROM budgets b LEFT JOIN actuals a ON a.budget_id=b.id GROUP BY b.id ORDER BY b.period DESC,b.name`);defer rows.Close();var out[]Budget;for rows.Next(){var b Budget;rows.Scan(&b.ID,&b.Name,&b.Department,&b.BudgetCents,&b.SpentCents,&b.Period,&b.CreatedAt);out=append(out,b)};return out,nil}
func(db *DB)AddActual(a *Actual)error{res,err:=db.Exec(`INSERT INTO actuals(budget_id,description,amount_cents,date)VALUES(?,?,?,?)`,a.BudgetID,a.Description,a.AmountCents,a.Date);if err!=nil{return err};a.ID,_=res.LastInsertId();return nil}
func(db *DB)DeleteBudget(id int64){db.Exec(`DELETE FROM actuals WHERE budget_id=?`,id);db.Exec(`DELETE FROM budgets WHERE id=?`,id)}
func(db *DB)Stats()(map[string]interface{},error){var budgets int;var budget,spent int64;db.QueryRow(`SELECT COUNT(*) FROM budgets`).Scan(&budgets);db.QueryRow(`SELECT COALESCE(SUM(budget_cents),0) FROM budgets`).Scan(&budget);db.QueryRow(`SELECT COALESCE(SUM(amount_cents),0) FROM actuals`).Scan(&spent);return map[string]interface{}{"budgets":budgets,"total_budget_cents":budget,"total_spent_cents":spent},nil}
